// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: service_a/service_a.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	shared "github.com/phev8/go_commons/pkg/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServiceAObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition bool   `protobuf:"varint,3,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *ServiceAObject) Reset() {
	*x = ServiceAObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_a_service_a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAObject) ProtoMessage() {}

func (x *ServiceAObject) ProtoReflect() protoreflect.Message {
	mi := &file_service_a_service_a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAObject.ProtoReflect.Descriptor instead.
func (*ServiceAObject) Descriptor() ([]byte, []int) {
	return file_service_a_service_a_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAObject) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceAObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAObject) GetCondition() bool {
	if x != nil {
		return x.Condition
	}
	return false
}

type CombinedObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonObject  *shared.CommonObject `protobuf:"bytes,1,opt,name=commonObject,proto3" json:"commonObject,omitempty"`
	ServiceObject *ServiceAObject      `protobuf:"bytes,2,opt,name=serviceObject,proto3" json:"serviceObject,omitempty"`
}

func (x *CombinedObject) Reset() {
	*x = CombinedObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_a_service_a_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombinedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedObject) ProtoMessage() {}

func (x *CombinedObject) ProtoReflect() protoreflect.Message {
	mi := &file_service_a_service_a_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedObject.ProtoReflect.Descriptor instead.
func (*CombinedObject) Descriptor() ([]byte, []int) {
	return file_service_a_service_a_proto_rawDescGZIP(), []int{1}
}

func (x *CombinedObject) GetCommonObject() *shared.CommonObject {
	if x != nil {
		return x.CommonObject
	}
	return nil
}

func (x *CombinedObject) GetServiceObject() *ServiceAObject {
	if x != nil {
		return x.ServiceObject
	}
	return nil
}

var File_service_a_service_a_proto protoreflect.FileDescriptor

var file_service_a_service_a_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x1a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8b, 0x01, 0x0a, 0x0e, 0x43,
	0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x38, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x32, 0xd7, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x12, 0x3e, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a,
	0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x44, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x45, 0x0a, 0x11, 0x67,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x68, 0x65, 0x76, 0x38, 0x2f, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x41, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_a_service_a_proto_rawDescOnce sync.Once
	file_service_a_service_a_proto_rawDescData = file_service_a_service_a_proto_rawDesc
)

func file_service_a_service_a_proto_rawDescGZIP() []byte {
	file_service_a_service_a_proto_rawDescOnce.Do(func() {
		file_service_a_service_a_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_a_service_a_proto_rawDescData)
	})
	return file_service_a_service_a_proto_rawDescData
}

var file_service_a_service_a_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_a_service_a_proto_goTypes = []interface{}{
	(*ServiceAObject)(nil),       // 0: service_a.ServiceAObject
	(*CombinedObject)(nil),       // 1: service_a.CombinedObject
	(*shared.CommonObject)(nil),  // 2: common.CommonObject
	(*shared.RequestObject)(nil), // 3: common.RequestObject
}
var file_service_a_service_a_proto_depIdxs = []int32{
	2, // 0: service_a.CombinedObject.commonObject:type_name -> common.CommonObject
	0, // 1: service_a.CombinedObject.serviceObject:type_name -> service_a.ServiceAObject
	3, // 2: service_a.ServiceA.getCommonObject:input_type -> common.RequestObject
	3, // 3: service_a.ServiceA.getServiceObject:input_type -> common.RequestObject
	3, // 4: service_a.ServiceA.getCombinedObject:input_type -> common.RequestObject
	2, // 5: service_a.ServiceA.getCommonObject:output_type -> common.CommonObject
	0, // 6: service_a.ServiceA.getServiceObject:output_type -> service_a.ServiceAObject
	1, // 7: service_a.ServiceA.getCombinedObject:output_type -> service_a.CombinedObject
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_a_service_a_proto_init() }
func file_service_a_service_a_proto_init() {
	if File_service_a_service_a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_a_service_a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_a_service_a_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombinedObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_a_service_a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_a_service_a_proto_goTypes,
		DependencyIndexes: file_service_a_service_a_proto_depIdxs,
		MessageInfos:      file_service_a_service_a_proto_msgTypes,
	}.Build()
	File_service_a_service_a_proto = out.File
	file_service_a_service_a_proto_rawDesc = nil
	file_service_a_service_a_proto_goTypes = nil
	file_service_a_service_a_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceAClient is the client API for ServiceA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceAClient interface {
	GetCommonObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*shared.CommonObject, error)
	GetServiceObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*ServiceAObject, error)
	GetCombinedObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*CombinedObject, error)
}

type serviceAClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceAClient(cc grpc.ClientConnInterface) ServiceAClient {
	return &serviceAClient{cc}
}

func (c *serviceAClient) GetCommonObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*shared.CommonObject, error) {
	out := new(shared.CommonObject)
	err := c.cc.Invoke(ctx, "/service_a.ServiceA/getCommonObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAClient) GetServiceObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*ServiceAObject, error) {
	out := new(ServiceAObject)
	err := c.cc.Invoke(ctx, "/service_a.ServiceA/getServiceObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAClient) GetCombinedObject(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*CombinedObject, error) {
	out := new(CombinedObject)
	err := c.cc.Invoke(ctx, "/service_a.ServiceA/getCombinedObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAServer is the server API for ServiceA service.
type ServiceAServer interface {
	GetCommonObject(context.Context, *shared.RequestObject) (*shared.CommonObject, error)
	GetServiceObject(context.Context, *shared.RequestObject) (*ServiceAObject, error)
	GetCombinedObject(context.Context, *shared.RequestObject) (*CombinedObject, error)
}

// UnimplementedServiceAServer can be embedded to have forward compatible implementations.
type UnimplementedServiceAServer struct {
}

func (*UnimplementedServiceAServer) GetCommonObject(context.Context, *shared.RequestObject) (*shared.CommonObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommonObject not implemented")
}
func (*UnimplementedServiceAServer) GetServiceObject(context.Context, *shared.RequestObject) (*ServiceAObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceObject not implemented")
}
func (*UnimplementedServiceAServer) GetCombinedObject(context.Context, *shared.RequestObject) (*CombinedObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCombinedObject not implemented")
}

func RegisterServiceAServer(s *grpc.Server, srv ServiceAServer) {
	s.RegisterService(&_ServiceA_serviceDesc, srv)
}

func _ServiceA_GetCommonObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.RequestObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAServer).GetCommonObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_a.ServiceA/GetCommonObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAServer).GetCommonObject(ctx, req.(*shared.RequestObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceA_GetServiceObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.RequestObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAServer).GetServiceObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_a.ServiceA/GetServiceObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAServer).GetServiceObject(ctx, req.(*shared.RequestObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceA_GetCombinedObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.RequestObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAServer).GetCombinedObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_a.ServiceA/GetCombinedObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAServer).GetCombinedObject(ctx, req.(*shared.RequestObject))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service_a.ServiceA",
	HandlerType: (*ServiceAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCommonObject",
			Handler:    _ServiceA_GetCommonObject_Handler,
		},
		{
			MethodName: "getServiceObject",
			Handler:    _ServiceA_GetServiceObject_Handler,
		},
		{
			MethodName: "getCombinedObject",
			Handler:    _ServiceA_GetCombinedObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_a/service_a.proto",
}
